title: "Виталий Кузьмин"
description: "Резюме Team Lead / Backend Lead"
remote_theme: jekyll/minima
minima:
  skin: dark
  hide_site_feed_link: true
  show_excerpts: false
author:
  name: Vitaliy Kuzmin
  email: "viton930@gmail.com"

google_analytics: G-CEX9LP3BVB
